### ISSUE TITLE
design-changes

### ISSUE THREAD

**Issue by Kycedron** [NovaDevelopersCo/NovaDev-Frontend#31]
change zoomish to BynarysDE(маленькая ByDEV)
move dark theme button to the right 
make button exit smaller and delete word exit move it to center of the list
move login to center
сменить зумиша на БунарисДЕВ (БУдев)
подвинуть кнопку темной темы вправо
кнопку выхода сделать по центру и убрать слово выйти 
подвинуть логин в центр

**Comment by Kycedron** [comment]
![изображение](https://github.com/NovaDevelopersCo/NovaDev-Frontend/assets/138807475/df5bef0b-1cef-4dc4-8f6f-4132f497e937)
страница 404 поломана 
пофикси и будь умничкой

**Comment by kowkaLYT** [comment]
![image](https://github.com/NovaDevelopersCo/NovaDev-Frontend/assets/153850235/1d0abec6-f102-4897-a4a7-827e18560c25)
 цветовая палитра для проекта
